language: php
sudo: false
dist: xenial

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

install:
  - travis_retry composer update -n --prefer-dist --prefer-stable

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit -v

jobs:
  include:
    - php: 7.4
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - travis_retry composer update -n --prefer-dist
    - php: 7.4
      env: SYMFONY_REQUIRE="5.3.*"
      install:
        - travis_retry composer update -n --prefer-dist

    - php: 8.0
      env: SYMFONY_REQUIRE="4.4.*"
      install:
        - travis_retry composer update -n --prefer-dist
    - php: 8.0
      env: SYMFONY_REQUIRE="5.3.*"
      install:
        - travis_retry composer update -n --prefer-dist